name: eqtl
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - r-base=4.1.3
  - python=3.9.12
  - r-Rcpp=1.0.9                                                     
  - r-backports=1.4.1
  - r-reprex=2.0.2
  - r-httr=1.4.4          
  - r-pillar=1.8.1                          
  - r-lattice=0.20-45
  - r-assertthat=0.2.1 
  - r-utf8=1.2.2
  - r-R6=2.5.1
  - r-cellranger=1.1.0
  - r-plyr=1.8.8
  - r-rlang=1.0.6
  - r-googlesheets4=1.0.1
  - r-curl=4.3.3
  - r-readxl=1.4.1
  - r-rstudioapi=0.14
  - r-textshaping=0.3.6
  - r-labeling=0.4.2
  - r-googledrive=2.0.0
  - r-munsell=0.5.0
  - r-broom=1.0.2 
  - r-compiler=4.1.3
  - r-modelr=0.1.10
  - r-systemfonts=1.0.4 
  - r-pkgconfig=2.0.3
  - r-tidyselect=1.2.0
  - r-quadprog=1.5-8
  - r-fansi=1.0.3
  - r-crayon=1.5.2
  - r-tzdb=0.3.0 
  - r-dbplyr=2.2.1
  - r-withr=2.5.0
  - r-grid=4.1.3
  - r-Quandl=2.11.0
  - r-jsonlite=1.8.4
  - r-gtable=0.3.1
  - r-lifecycle=1.0.3
  - r-DBI=1.1.3
  - r-magrittr=2.0.3
  - r-scales=1.2.1
  - r-cli=3.6.0
  - r-stringi=1.7.12
  - r-farver=2.1.1
  - r-fs=1.6.0
  - r-xml2=1.3.3
  - r-ragg=1.2.5
  - r-ellipsis=0.3.2
  - r-generics=0.1.3
  - r-vctrs=0.5.1
  - r-tools=4.1.3
  - r-glue=1.6.2
  - r-hms=1.1.2
  - r-colorspace=2.0-3 
  - r-gargle=1.2.1
  - r-rvest=1.0.3
  - r-haven=2.5.1
  - r-SNPRelate=1.28.0
  - r-gdsfmt=1.30.0
  - r-patchwork=1.1.2 
  - r-reshape2=1.4.4
  - r-tidyquant=1.0.6
  - r-quantmod=0.4.20
  - r-TTR=0.24.3
  - r-PerformanceAnalytics=2.0.4
  - r-xts=0.12.2
  - r-zoo=1.8-11
  - r-lubridate=1.9.0
  - r-timechange=0.2.0
  - r-forcats=0.5.2
  - r-stringr=1.5.0
  - r-dplyr=1.0.10
  - r-purrr=1.0.1
  - r-readr=2.1.3
  - r-tidyr=1.2.1
  - r-tibble=3.1.8
  - r-ggplot2=3.4.0
  - r-tidyverse=1.3.2
  - r-ggpubr=0.5.0
